name: test1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  objectbox: ^1.3.0
  objectbox_flutter_libs: ^1.3.0
  shared_preferences: ^2.0.11
  flutter_svg: ^1.0.0
  get: ^4.6.1
  get_storage: ^2.0.3
  internet_connection_checker: ^0.0.1+3
  intl: ^0.17.0
  flutter_icons: ^1.1.0
  http: ^0.13.4
  cached_network_image: ^3.2.0
  image_picker: ^0.8.4+10
  json_serializable: ^6.1.5
  json_annotation: ^4.4.0
  ntp: ^2.0.0
  screen: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  objectbox_generator: ^1.3.0
  build_runner: ^2.1.7


flutter:
  uses-material-design: true
  assets:
    - assets/png/
  fonts:
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/OpenSans-SemiBold.ttf
